### ISSUE TITLE
Re-write project renderer to not have a really bad method for determining 'release'

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-policy#96]
This method of rendering causes every project to loop through every transaction every time a project is rendered.  This is especially bad when the search_sync tool is walking through every transaction, it renders a project, which in turn walks through each transaction again.  for a project that has never released any data and has a lot of transactions, it will, in fact, cause an exponential slowdown.

https://github.com/pacifica/pacifica-policy/blob/c7e0b89e85096665f2f587ed520923fb2708fe9c/pacifica/policy/search/projects.py#L82-L87

**Comment by dmlb2000** [comment]
@karcaw Pull #99 adds a performance test that creates 10k transactions against a proposal that aren't released. That check tests this function and it returns in less than a second. That means for 500k transactions associated with a project this method should only cost 50 seconds max.

**Comment by dmlb2000** [comment]
@karcaw if you look at the second commit of the pull request, the logic for determining the released state of the project takes the longest. Almost 2 minutes on my gaming desktop, so for 500k transactions that would be almost an hour and a half per transaction of the project and the project itself to determine the release state of the project.

So are you thinking the method https://github.com/pacifica/pacifica-policy/blob/c7e0b89e85096665f2f587ed520923fb2708fe9c/pacifica/policy/search/projects.py#L74-L79 needs to be updated to use an attribute of the project to determine release state?

**Comment by dmlb2000** [comment]
Here's the travis build for the method that's taking too long.

https://travis-ci.org/pacifica/pacifica-policy/jobs/554344255

172 seconds in travis is also quite slow for 10k transactions not released. Then if you have 500k transactions, none of which are released, the algorithm has to walk for 2.4 hours to determine the release state of the project. This is particularly bad because this walk needs to be done for every transaction and the project itself and that's how you get `O(n^2)` algorithm.

I believe the release state of the project is important to render and can't be removed. That attribute determines if users can query elasticsearch for released data.

Are there any suggestions on how to determine the released state of the project that is `O(1)`?

**Comment by karcaw** [comment]
This SQL query renders pretty quick

```select transaction_id from transsip,transactions,transactionuser  where  transsip.project_id='17797' and transactions.id=transsip.id_id and transactionuser.relationship_id='be0cd1a7-2ab1-463d-9a3e-94b513ddd558' and transactionuser.transaction_id=transactions.id;```

**Comment by karcaw** [comment]
We could also re-implement this method to match what MyEMSL needs, as they want every approved project to reflect as 'released'.
